# dependabot.yml
# Author: D.A.Pelasgus

version: 2
on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust as necessary)
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
