name: Update README with Contributions

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (adjust as necessary)
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Environment
        run: sudo apt-get install jq

      - name: Fetch and Update README with Contributions
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}
        run: |
          chmod +x scripts/*.sh
          ./scripts/main.sh

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with contributions" || echo "No changes to commit"
          git push -u origin main
